### ISSUE TITLE
Graph not filling up correctly

### ISSUE THREAD

**Issue by joanjgm** [Piero24/acemagic-S1-panel-conf#1]
I've been using this theme for a couple of weeks and I've notices that de CPU and Mem graph are not showing the right % fill

![download](https://github.com/user-attachments/assets/d6019f77-6c86-4a4f-8fe9-47c186ad2163)

As seen on the image if the RAM is at 51% the graph should be filled up to the half

Is there any fix?

**Comment by Piero24** [comment]
Hi @joanjgm, Unfortunately, I couldn’t find a list of the parameters in the original repo when I made the theme. If I’m not mistaken, the table should be as follows (based on [this file](https://github.com/tjaworski/AceMagic-S1-LED-TFT-Linux/blob/main/s1panel/sensors/memory.js)):

1.	**Total memory** (total memory in bytes): Use {0}.
2.	**Swap total** (swap_total in bytes): Use {1}.
3.	**Memory usage percentage** (usage): Use {2}.
4.	**Memory usage history** (in percentages): Use {3}.
5.	**Swap usage percentage** (swap): Use {4}.
6.	**Swap usage history** (in percentages): Use {5}.
7.	**Free memory** (free memory in bytes): Use {6}.
8.	**Free memory history**: Use {7}.
9.	**Cached memory** (cached in bytes): Use {8}.
10.	**Cached memory history**: Use {9}.
11.	**Active memory** (active memory in bytes): Use {10}.
12.	**Active memory history**: Use {11}.
13.	**Used swap memory** (swap_used in bytes): Use {12}.
14.	**Used swap memory history**: Use {13}.
15.	**Formatted active memory** (in GB/MB/KB): Use {14}.
16.	**Formatted used swap memory** (in GB/MB/KB): Use {15}.

Therefore, the correct parameter should be **number 2** (which is the currently used one). I believe the sampling for the graph is done every few seconds and is different from the percentage, so there may be a difference between the two.

But it’s better to confirm with @tjaworski, who will surely know if I’m missing something.

**Comment by tjaworski** [comment]
I'll take a look, not sure why it wouldn't be at 50% mark. unless it grabbed an older point in the history.

**Comment by joanjgm** [comment]
I haven't edited the default values except for the spacing between the field name and the variable, for example where there was: Swap:         {15} I changed it to Swap:{15}, no more than that. Hope you get to the fix

**Comment by joanjgm** [comment]
quick update @tjaworski @Piero24 it's now on 66% and still not even filling half the graph

![image](https://github.com/user-attachments/assets/532f30ce-4a2f-4f48-9038-a26047a34b70)

**Comment by Piero24** [comment]
In the settings, the parameter is the same ({2}), so there shouldn’t be any issues at the configuration level.

<table>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d3183412-5717-4088-b5a8-da8424e15765" alt="Image 1" width="1000"/></td>
    <td><img src="https://github.com/user-attachments/assets/2eff9302-cb7c-4b99-b597-f7a8b6d4683f" alt="Image 2" width="1000"/></td>
  </tr>
</table>

**Comment by joanjgm** [comment]
> In the settings, the parameter is the same ({2}), so there shouldn’t be any issues at the configuration level.
> 
> <img alt="Image 1" width="1000" src="https://private-user-images.githubusercontent.com/32714047/383231037-d3183412-5717-4088-b5a8-da8424e15765.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjQ2MjcsIm5iZiI6MTczMDgyNDMyNywicGF0aCI6Ii8zMjcxNDA0Ny8zODMyMzEwMzctZDMxODM0MTItNTcxNy00MDg4LWI1YTgtZGE4NDI0ZTE1NzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE2MzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhN2MwNTViYWYwM2ZmODE4ODRkMDhmN2UwNmM5Njc1N2Q4Nzc0ODQ4OTVjZWZkZDJiODUzOTdjMjQ5MWExMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A78XJqChhyz9mErHlAz61vx6ciew_5JnR53pBnXco3c">	<img alt="Image 2" width="1000" src="https://private-user-images.githubusercontent.com/32714047/383231048-2eff9302-cb7c-4b99-b597-f7a8b6d4683f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjQ2MjcsIm5iZiI6MTczMDgyNDMyNywicGF0aCI6Ii8zMjcxNDA0Ny8zODMyMzEwNDgtMmVmZjkzMDItY2I3Yy00Yjk5LWI1OTctZjdhOGI2ZDQ2ODNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE2MzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNjE2ZGIwZGM2NTZjYWM2MTU0MDA2MjlkYjhjYjc5NjhlNjFiZGRlNzgzMWM2NTczOTQ4NTliOWFmNjUzYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sVOkvtKDht4rgr-qXi5Pbih3LztB6SXlgObfZuubj_I">

Yep, that's exactly how I have it, I've never edited those values before

@Piero24 can you add some heavy load to your S1 and see if it happens the same to you?

**Comment by tjaworski** [comment]
ok, it has been fixed with https://github.com/tjaworski/AceMagic-S1-LED-TFT-Linux/pull/36 thanks for your help.

**Comment by joanjgm** [comment]
In deed it's showing correctly now, thanks @tjaworski 

<img width="455" alt="image" src="https://github.com/user-attachments/assets/e3146a78-6635-4e98-a9e5-1168d79a327a">
